#!/usr/bin/env bash
#A bash script that give information about the holbertonschool file

file="school"
if [[ -e $file ]]; then
    echo "$file file exists"
    if [[ ! -s $file ]]; then
	echo "$file file is empty"
    elif [[ -s $file ]]; then
	echo "$file file is not empty"
    fi
    if [[ -f $file ]]; then
	echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi
